[package]
name = "tdm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
eyre = "0.6.12"
reqwest = "0.11.25"
tokio = { version = "1.36.0", features = ["full"] }
trauma = "2.2.4"
